/**
 * @file src/types.ts
 * @version 4.9.3-EMG
 * @engine EMG Core Neural Code and Documentation Optimizer Engine
 * @description Sovereign type definitions providing clean architectural models,
 * strict structural immutability, and zero-cost type safety for chess runtime orchestration.
 */

/* ============================================================================
 * ENUMS & DISCRIMINATED UNIONS
 * ========================================================================= */

/**
 * Competitive and cooperative game orchestration modes.
 */
export const GameMode = {
  PVP: 'PVP',
  PVE: 'PVE',
  PVD: 'PVD',
  AVA: 'AVA',
} as const;

export type GameMode = (typeof GameMode)[keyof typeof GameMode];

/**
 * Cognitive processing and depth levels for synthetic chess engines.
 */
export const GameDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
} as const;

export type GameDifficulty = (typeof GameDifficulty)[keyof typeof GameDifficulty];

/**
 * Visual themes and styling presets for board rendering.
 */
export const BoardTheme = {
  CRUCIBLE: 'CRUCIBLE',
  CYBER: 'CYBER',
  OBSIDIAN: 'OBSIDIAN',
  CLASSIC: 'CLASSIC',
} as const;

export type BoardTheme = (typeof BoardTheme)[keyof typeof BoardTheme];

/**
 * Piece polarity identifier representing board color alignment.
 * - `'w'`: White piece / player
 * - `'b'`: Black piece / player
 */
export type PieceColor = 'w' | 'b';

/**
 * Emotional spectrum states driving synthetic Dalek telemetry and speech synthesis.
 */
export type DalekEmotion =
  | 'prophetic'
  | 'maniacal'
  | 'furious'
  | 'calculating'
  | 'victorious'
  | 'panicked';

/**
 * Theological rhetorical profiles driving divine discourse synthesis.
 */
export type JesusTone =
  | 'serene'
  | 'righteous'
  | 'compassionate'
  | 'majestic'
  | 'wrathful';

/* ============================================================================
 * GAMEPLAY & BOARD STATE MODELS
 * ========================================================================= */

/**
 * Immutable log entry detailing an executed chess move.
 */
export interface MoveLog {
  /** Unique identifier for the move record */
  readonly id: string;
  /** Source square coordinate in algebraic notation (e.g., 'e2') */
  readonly from: string;
  /** Target square coordinate in algebraic notation (e.g., 'e4') */
  readonly to: string;
  /** Piece type descriptor (e.g., 'p', 'n', 'b', 'r', 'q', 'k') */
  readonly piece: string;
  /** Color of the piece executed */
  readonly color: PieceColor;
  /** Standard Algebraic Notation representation of the move (e.g., 'e4', 'Nxf3+') */
  readonly san: string;
  /** Formatted timestamp indicating when the move was registered */
  readonly timestamp: string;
}

/**
 * Immutable ledger tracking captured board assets categorized by piece color.
 */
export interface CapturedPieces {
  /** Pieces captured from the White player */
  readonly w: readonly string[];
  /** Pieces captured from the Black player */
  readonly b: readonly string[];
}

/* ============================================================================
 * SYNTHESIS & DIALOGUE TELEMETRY
 * ========================================================================= */

/**
 * Telemetry payload for Dalek entity dialogue generation and vocalization.
 */
export interface DalekDialogue {
  /** Synthesized verbal output */
  readonly text: string;
  /** Emotional state modulating vocal timbre and cadence */
  readonly emotion: DalekEmotion;
  /** Prophecy intensity metric represented as a normalized percentage (0–100) */
  readonly prophecyLevel: number;
  /** Unix epoch timestamp of dialogue dispatch */
  readonly timestamp: number;
}

/**
 * Synchronized telemetry record capturing reciprocal debate between AI entities.
 */
export interface DebateDialogue {
  /** Verbal discourse generated by Dalek Caan */
  readonly caanText: string;
  /** Emotional state of Dalek Caan */
  readonly caanEmotion: DalekEmotion;
  /** Verbal discourse generated by Jesus entity */
  readonly jesusText: string;
  /** Rhetorical tone governing the Jesus entity output */
  readonly jesusTone: JesusTone;
  /** Prophecy index scalar accompanying the dialectical exchange (0–100) */
  readonly prophecyLevel: number;
  /** Unix epoch timestamp of the debate event */
  readonly timestamp: number;
}

/* ============================================================================
 * SYSTEM & CONFIGURATION PROFILES
 * ========================================================================= */

/**
 * Immutable game configuration profile governing active rules, themes, and audio levels.
 */
export interface GameSettings {
  /** Active orchestration mode (PVP, PVE, PVD, AVA) */
  readonly mode: GameMode;
  /** Target AI processing difficulty */
  readonly difficulty: GameDifficulty;
  /** Active visual theme */
  readonly theme: BoardTheme;
  /** Assigned color for human player */
  readonly playerColor: PieceColor;
  /** Global audio mute toggle */
  readonly muteSounds: boolean;
  /** Master speech synthesizer volume scalar clamped between [0.0, 1.0] */
  readonly synthesizerVolume: number;
}